---
title: "Experiment"
author: "Natacha Walker"
date: "26/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Load libraries
library(pacman)
p_load(tidyverse, tidyr, reshape2, data.table, dplyr, Hmisc, viridis, brms, bayesplot)

#Set working directory and load in the data
#setwd("C:/Users/Natacha/Dropbox/Natacha/Aarhus Universitet/4. Semester/Social and Cultural Dynamics in Cognition")
d1 <- read_csv("other-self-obj.csv")
d2 <- read_csv("self-obj-other.csv")
d3 <- read_csv("obj-other-self.csv")

```

## Preprossesing the data

```{r}

#Removing column
d1$Timestamp <- NULL
d1$`Have you read text one all the way through?` <- NULL
d1$`Have you read text two all the way through?` <- NULL
d1$`Have you read text three all the way through?` <- NULL
d2$Timestamp <- NULL
d2$`Have you read text one all the way through?` <- NULL
d2$`Have you read text two all the way through?` <- NULL
d2$`Have you read text three all the way through?` <- NULL
d3$Timestamp <- NULL
d3$`Have you read text one all the way through?` <- NULL
d3$`Have you read text two all the way through?` <- NULL
d3$`Have you read text three all the way through?` <- NULL
d3$X1 <- NULL

#8 rows (participants is excluded due to data loss), all in the other-self-obj order
d1 <- d1[rowSums(is.na(d1)) != ncol(d1), ]

#2 participants are excluded due to only pressing 1 all the way through 
d1 <- d1[-c(8,9),]

#Make a column called participant ID just with numbers from 1-x
d1 <- mutate(d1, ID = seq(nrow(d1)))
d2 <- mutate(d2, ID = seq(27,60))
d3 <- mutate(d3, ID = seq(61,93))

#Placing it before all the other columns
d1 <- d1[,c(ncol(d1),1:(ncol(d1)-1))]
d2 <- d2[,c(ncol(d2),1:(ncol(d2)-1))]
d3 <- d3[,c(ncol(d3),1:(ncol(d3)-1))]

#Making the data long format for all three datasets
d1 <- d1%>% 
  unite(Disturbed, Disturbed, Disturbed_1, Disturbed_2) %>% 
  unite(Softhearted, Softhearted, Softhearted_1, Softhearted_2) %>% 
  unite(Caring, Caring, Caring_1, Caring_2) %>% 
  unite(Moved, Moved, Moved_1, Moved_2) %>% 
  unite(Troubled, Troubled, Troubled_1, Troubled_2) %>% 
  unite(Understanding, Understanding, Understanding_1, Understanding_2) %>%
  unite(Tense, Tense, Tense_1, Tense_2) %>%
  unite(Distressed, Distressed, Distressed_1, Distressed_2) %>%
  unite(Uneasy, Uneasy, Uneasy_1, Uneasy_2) %>%
  unite(Warm, Warm, Warm_1, Warm_2) %>%
  unite(Compassionate, Compassionate, Compassionate_1, Compassionate_2) %>%
  unite(Worried, Worried, Worried_1, Worried_2) %>%
  unite(Sympathetic, Sympathetic, Sympathetic_1, Sympathetic_2) %>%
  unite(Bewildered, Bewildered, Bewildered_1, Bewildered_2) %>%
  unite(Upset, Upset, Upset_1, Upset_2) %>%
  unite(Alarmed, Alarmed, Alarmed_1, Alarmed_2) %>%
  unite(Affinity, Affinity, Affinity_1, Affinity_2) %>%
  unite(Depressed, Depressed, Depressed_1, Depressed_2) %>%
  unite(Tender, Tender, Tender_1, Tender_2) %>%
  unite(Perturbed, Perturbed, Perturbed_1, Perturbed_2) %>%
  unite(Grieved, Grieved, Grieved_1, Grieved_2) %>%
  unite(Commiserative, Commiserative, Commiserative_1, Commiserative_2) %>%
  unite(Touched, Touched, Touched_1, Touched_2) %>%
  unite(Concerned, Concerned, Concerned_1, Concerned_2) %>%
  separate_rows(5:28, sep = "_")

d2 <- d2%>% 
  unite(Disturbed, Disturbed, Disturbed_1, Disturbed_2) %>% 
  unite(Softhearted, Softhearted, Softhearted_1, Softhearted_2) %>% 
  unite(Caring, Caring, Caring_1, Caring_2) %>% 
  unite(Moved, Moved, Moved_1, Moved_2) %>% 
  unite(Troubled, Troubled, Troubled_1, Troubled_2) %>% 
  unite(Understanding, Understanding, Understanding_1, Understanding_2) %>%
  unite(Tense, Tense, Tense_1, Tense_2) %>%
  unite(Distressed, Distressed, Distressed_1, Distressed_2) %>%
  unite(Uneasy, Uneasy, Uneasy_1, Uneasy_2) %>%
  unite(Warm, Warm, Warm_1, Warm_2) %>%
  unite(Compassionate, Compassionate, Compassionate_1, Compassionate_2) %>%
  unite(Worried, Worried, Worried_1, Worried_2) %>%
  unite(Sympathetic, Sympathetic, Sympathetic_1, Sympathetic_2) %>%
  unite(Bewildered, Bewildered, Bewildered_1, Bewildered_2) %>%
  unite(Upset, Upset, Upset_1, Upset_2) %>%
  unite(Alarmed, Alarmed, Alarmed_1, Alarmed_2) %>%
  unite(Affinity, Affinity, Affinity_1, Affinity_2) %>%
  unite(Depressed, Depressed, Depressed_1, Depressed_2) %>%
  unite(Tender, Tender, Tender_1, Tender_2) %>%
  unite(Perturbed, Perturbed, Perturbed_1, Perturbed_2) %>%
  unite(Grieved, Grieved, Grieved_1, Grieved_2) %>%
  unite(Commiserative, Commiserative, Commiserative_1, Commiserative_2) %>%
  unite(Touched, Touched, Touched_1, Touched_2) %>%
  unite(Concerned, Concerned, Concerned_1, Concerned_2) %>%
  separate_rows(5:28, sep = "_")

d3 <- d3%>% 
  unite(Disturbed, Disturbed, Disturbed_1, Disturbed_2) %>% 
  unite(Softhearted, Softhearted, Softhearted_1, Softhearted_2) %>% 
  unite(Caring, Caring, Caring_1, Caring_2) %>% 
  unite(Moved, Moved, Moved_1, Moved_2) %>% 
  unite(Troubled, Troubled, Troubled_1, Troubled_2) %>% 
  unite(Understanding, Understanding, Understanding_1, Understanding_2) %>%
  unite(Tense, Tense, Tense_1, Tense_2) %>%
  unite(Distressed, Distressed, Distressed_1, Distressed_2) %>%
  unite(Uneasy, Uneasy, Uneasy_1, Uneasy_2) %>%
  unite(Warm, Warm, Warm_1, Warm_2) %>%
  unite(Compassionate, Compassionate, Compassionate_1, Compassionate_2) %>%
  unite(Worried, Worried, Worried_1, Worried_2) %>%
  unite(Sympathetic, Sympathetic, Sympathetic_1, Sympathetic_2) %>%
  unite(Bewildered, Bewildered, Bewildered_1, Bewildered_2) %>%
  unite(Upset, Upset, Upset_1, Upset_2) %>%
  unite(Alarmed, Alarmed, Alarmed_1, Alarmed_2) %>%
  unite(Affinity, Affinity, Affinity_1, Affinity_2) %>%
  unite(Depressed, Depressed, Depressed_1, Depressed_2) %>%
  unite(Tender, Tender, Tender_1, Tender_2) %>%
  unite(Perturbed, Perturbed, Perturbed_1, Perturbed_2) %>%
  unite(Grieved, Grieved, Grieved_1, Grieved_2) %>%
  unite(Commiserative, Commiserative, Commiserative_1, Commiserative_2) %>%
  unite(Touched, Touched, Touched_1, Touched_2) %>%
  unite(Concerned, Concerned, Concerned_1, Concerned_2) %>%
  separate_rows(5:28, sep = "_")


d1$ID <- factor(d1$ID)
d2$ID <- factor(d2$ID)
d3$ID <- factor(d3$ID)

#Making the values as integer
d1[,5:28] <- sapply(d1[,5:28],as.integer)
d1$age <- as.integer(d1$age)

d2[,5:28] <- sapply(d2[,5:28],as.integer)
d2$age <- as.integer(d2$age)

d3[,5:28] <- sapply(d3[,5:28],as.integer)
d3$age <- as.integer(d3$age)

#making a condition column and calling it the condition names
d1 <- d1%>% group_by(ID) %>% mutate(condition = row_number())

d1$condition[d1$condition == "1"] <- "imagine_other"
d1$condition[d1$condition == "2"] <- "imagine_self"
d1$condition[d1$condition == "3"] <- "control"

d2 <- d2%>% group_by(ID) %>% mutate(condition = row_number())

d2$condition[d2$condition == "3"] <- "imagine_other"
d2$condition[d2$condition == "1"] <- "imagine_self"
d2$condition[d2$condition == "2"] <- "control"

d3 <- d3%>% group_by(ID) %>% mutate(condition = row_number())

d3$condition[d3$condition == "2"] <- "imagine_other"
d3$condition[d3$condition == "3"] <- "imagine_self"
d3$condition[d3$condition == "1"] <- "control"

#Binding the dataframes together
d_n <- rbind(d1,d2,d3)

#Then placing the conditions in front of the values (function is borrowed)

moveme <- function (invec, movecommand) {
  movecommand <- lapply(strsplit(strsplit(movecommand, ";")[[1]], 
                                 ",|\\s+"), function(x) x[x != ""])
  movelist <- lapply(movecommand, function(x) {
    Where <- x[which(x %in% c("before", "after", "first", 
                              "last")):length(x)]
    ToMove <- setdiff(x, Where)
    list(ToMove, Where)
  })
  myVec <- invec
  for (i in seq_along(movelist)) {
    temp <- setdiff(myVec, movelist[[i]][[1]])
    A <- movelist[[i]][[2]][1]
    if (A %in% c("before", "after")) {
      ba <- movelist[[i]][[2]][2]
      if (A == "before") {
        after <- match(ba, temp) - 1
      }
      else if (A == "after") {
        after <- match(ba, temp)
      }
    }
    else if (A == "first") {
      after <- 0
    }
    else if (A == "last") {
      after <- length(myVec)
    }
    myVec <- append(temp, values = movelist[[i]][[1]], after = after)
  }
  myVec
}


d_n <- d_n[moveme(names(d_n), "condition before Disturbed")]

#Making a empathy and distress column and sum up values from specific columns
d_n$empathy <- NA
d_n$distress <- NA

for (i in 1:nrow(d_n)){
  
  d_n$empathy[i] <- sum(d_n[i,c(7, 8, 9, 11, 15, 16, 18, 22, 24, 27, 28, 29)])
  d_n$distress[i] <- sum(d_n[i, c(6, 10, 12, 13, 14, 17, 19, 20, 21, 23, 25, 26)])
}

#Save as csv
write.csv(d_n,"preprossesing_exam.csv")
 
```

#Analysis

```{r}

#load in the data
d <- read_csv("preprossesing_exam.csv")
d$X1 <- NULL

#How many participants, gender age, age sd
unique(d$ID)

information <- d %>%
 group_by(gender) %>%
 summarise(gender_count=n()/3, mean_age = mean(age), sd_age = sd(age), min = min(age), max = max(age))

#Define the model
m_e <- bf(empathy ~ 0 + condition + (1|ID))
m_d <- bf(distress ~ 0 + condition + (1|ID))

# Ask which priors need to be defined
get_prior(m_e, data = d, family = gaussian)
get_prior(m_d, data = d, family = gaussian)


################## I NEED TO FIX EVERYTHING UNDER THIS LINE ##########################

# Define the prior
prior<- c(
prior(normal(49,5), class = b), 
prior(normal(2,1), class = sd), 
prior(normal(1,.5), class = sigma))

# Draw the consequences of priors AND likelihood
emp_only <- brm(m_e,
d,
prior = prior,
sample_prior = "only",
iter = 2000,
warmup = 1000,
chains = 2,
cores = 2,
control = list(
  adapt_delta = 0.99,
  max_treedepth = 20))

dis_only <- brm(m_d,
d,
prior = prior,
sample_prior = "only",
iter = 2000,
warmup = 1000,
chains = 2,
cores = 2,
control = list(
  adapt_delta = 0.99,
  max_treedepth = 20))

# Prior Predictive Check
pp_check(emp_only, nsamples = 100)
pp_check(dis_only, nsamples = 100)

# Draw the consequences of priors AND likelihood
m_emp <- brm(m_e,
d,
prior = prior,
sample_prior = T,
iter = 2000,
warmup = 1000,
chains = 2,
cores = 2,
control = list(
  adapt_delta = 0.99,
  max_treedepth = 20)) #Adapt_delta = "How much should you correct your steps/-size/mass etc. default 0.8, riccardo's default = 0.99
#Max tree depth = How many steps in the future should you look into to avoid u-turns? default = 15, Riccardo's default = 20

m_dis <- brm(m_d,
d,
prior = prior,
sample_prior = T,
iter = 2000,
warmup = 1000,
chains = 2,
cores = 2,
control = list(
  adapt_delta = 0.99,
  max_treedepth = 20))

# Posterior Predictive Check
pp_check(m_emp, nsamples = 100)
pp_check(m_dis, nsamples = 100)

# - trace plots and trace rank plots
color_scheme_set("viridis")
mcmc_trace(m_emp) + theme_classic()
mcmc_rank_overlay(m_emp) + theme_classic()

mcmc_trace(m_dis) + theme_classic()
mcmc_rank_overlay(m_dis) + theme_classic()

#Check for warnings after the pp_check
summary(m_emp)
summary(m_dis)

# Has the model learned? The posteriors have moved or gotten more confident than the priors
plot(hypothesis(m_emp, "conditioncontrol > 0"))
plot(hypothesis(m_emp, "conditionimagine_other > 0"))
plot(hypothesis(m_emp, "conditionimagine_self > 0"))

plot(hypothesis(m_dis, "conditioncontrol > 0"))
plot(hypothesis(m_dis, "conditionimagine_other > 0"))
plot(hypothesis(m_dis, "conditionimagine_self > 0"))

# Hypothesis testing + updating check

plot(hypothesis(m_emp,"conditionimagine_other > conditionimagine_self"))
hypothesis(m_emp,"conditionimagine_other > conditionimagine_self")

plot(hypothesis(m_emp,"conditionimagine_other > conditioncontrol"))
hypothesis(m_emp,"conditionimagine_other > conditioncontrol")

plot(hypothesis(m_dis, "conditionimagine_self > conditionimagine_other"))
hypothesis(m_dis,"conditionimagine_self > conditionimagine_other")

plot(hypothesis(m_dis,"conditionimagine_self > conditioncontrol"))
hypothesis(m_dis,"conditionimagine_self > conditioncontrol")


#Plots
conditional_effects(m_emp)
plot(conditional_effects(m_emp), points=T)

conditional_effects(m_dis)
plot(conditional_effects(m_dis), points=T)

```

#Are empathy and distress correlated?

```{r}

d_other <- filter(d, condition == "imagine_other")

d_self <- filter(d, condition == "imagine_self")


d_scale <- d_other %>% mutate(
  scale_empathy = scale(empathy))

d_scale1 <- d_self %>% mutate(
  scale_distress = scale(distress))


#Virker ikke
d_scaled <- rbind(d_scale, d_scale1)

#scale

```


